/**
 * punch
 *
 * Takes attendance from a clock on a wall.
 *
 * POST { terminal_id, punches: [{ user, at, direction? }, ...] }
 *   header: x-terminal-secret
 *   -> 200 { accepted, duplicates, problems: [{ user, at, problem }] }
 *   -> 401 the secret is wrong, or the terminal is not one of ours
 *
 * ## Why this is its own function
 *
 * A biometric terminal has no login. `clock_in` and `clock_out` read
 * `auth.uid()` to work out whose attendance this is, and there is no
 * session behind a device bolted to a door frame. It authenticates with
 * a secret instead, issued once by `register_time_terminal` and stored
 * only as a bcrypt hash — so a support call cannot recover it and
 * neither can anybody who can impersonate one.
 *
 * ## Why the punch carries its own time
 *
 * A terminal that loses its network at 08:55 and reconnects at 17:30
 * sends the morning's punches when it reconnects. `clock_in` stamps
 * `now()`, which would file every one of them at half past five. `at`
 * is what the device recorded and is what gets stored.
 *
 * ## Why a bad punch does not fail the batch
 *
 * The caller is a device replaying what it has. One finger nobody
 * enrolled, in a hundred punches, must not stop the other ninety-nine —
 * and a non-2xx makes most of these devices send the whole batch again,
 * forever. Every punch is reported individually and the request
 * succeeds.
 *
 * ## The secret is not in this repository
 *
 * It is generated by the database and shown once. There is nothing to
 * configure here beyond the service-role key this function already has
 * in order to write attendance for somebody who is not signed in.
 */
import { createClient } from "jsr:@supabase/supabase-js@2";

import { serveFunction } from "../_shared/cors.ts";
import { punchDirection, punchTime } from "./punch.ts";

interface Punch {
  user?: string;
  at?: string;
  direction?: string;
}

function json(body: unknown, status = 200): Response {
  // `serveFunction` puts the CORS headers on whatever comes back, so
  // this only has to say what kind of body it is.
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

serveFunction("punch.failed", async (req: Request) => {
  if (req.method !== "POST") return json({ error: "POST only" }, 405);

  let body: { terminal_id?: string; punches?: Punch[] };
  try {
    body = await req.json();
  } catch {
    return json({ error: "Expected JSON" }, 400);
  }

  const terminalId = (body.terminal_id ?? "").trim();
  const offered = req.headers.get("x-terminal-secret") ?? "";
  if (!terminalId || !offered) {
    return json({ error: "A terminal identifies itself and proves it" }, 401);
  }

  const db = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { auth: { persistSession: false } },
  );

  // The comparison is bcrypt's own, in the database. There is nothing
  // to compare here: `receive-email` hashes nothing and so compares a
  // shared secret byte by byte itself, and copying that shape to sit
  // beside a hash check that has already happened would be decoration.
  const { data: ok, error } = await db.rpc("terminal_secret_matches", {
    p_terminal_id: terminalId,
    p_secret: offered,
  });
  if (error) return json({ error: "Could not check the terminal" }, 500);
  if (ok !== true) {
    // The same answer for a wrong secret and an unknown terminal. A
    // different one tells somebody probing which terminal IDs exist.
    return json({ error: "Not this terminal" }, 401);
  }

  const punches = Array.isArray(body.punches) ? body.punches : [];
  if (punches.length === 0) return json({ accepted: 0, duplicates: 0, problems: [] });

  let accepted = 0;
  let duplicates = 0;
  const problems: Array<{ user: string; at: string; problem: string }> = [];

  for (const p of punches) {
    const at = punchTime(p.at);
    const user = (p.user ?? "").trim();
    if (!at) {
      problems.push({ user, at: p.at ?? "", problem: "Unreadable time" });
      continue;
    }

    const { data, error: rpcError } = await db.rpc("record_terminal_punch", {
      p_terminal_id: terminalId,
      p_enrolment_no: user,
      p_punched_at: at,
      p_direction: punchDirection(p.direction),
    });

    if (rpcError) {
      problems.push({ user, at, problem: rpcError.message });
      continue;
    }
    const result = (data ?? {}) as {
      ok?: boolean;
      duplicate?: boolean;
      problem?: string;
    };
    if (result.duplicate) {
      duplicates++;
    } else if (result.ok) {
      accepted++;
    } else {
      problems.push({ user, at, problem: result.problem ?? "Refused" });
    }
  }

  return json({ accepted, duplicates, problems });
});
