// Produce a Web Push test vector with the reference implementation.
//
// Every key pair here is generated fresh and thrown away into the
// fixture. None of it is, or has ever been, a deployed key: the real
// VAPID private half is a function secret and appears nowhere in this
// repository. The fixture carries private keys because a test that
// cannot decrypt what it encrypted is not checking anything.
//
// http_ece is what web-push uses, which is what most of the world's web
// push traffic is encrypted by. Fixing the salt and both key pairs makes
// its output deterministic, so it can be checked into the repository and
// asserted against in CI where only Deno runs.
const crypto = require('crypto');
const ece = require('http_ece');
const webpush = require('web-push');

const b64 = (b) => Buffer.from(b).toString('base64url');

// The receiver: a browser. Generated here, then its private half is kept
// in the fixture so the Deno test can also decrypt what it produced.
const ua = crypto.createECDH('prime256v1');
ua.generateKeys();

// The sender's ephemeral key pair, fixed so the output does not move.
const as = crypto.createECDH('prime256v1');
as.generateKeys();

const authSecret = crypto.randomBytes(16);
const salt = crypto.randomBytes(16);
const plaintext = 'When I grow up, I want to be a watermelon';

const body = ece.encrypt(Buffer.from(plaintext), {
  version: 'aes128gcm',
  salt: b64(salt),
  privateKey: as,
  dh: b64(ua.getPublicKey()),
  authSecret: b64(authSecret),
  rs: 4096,
});

// Prove the vector round-trips through the reference implementation
// itself before anything is asserted against it.
const back = ece.decrypt(body, {
  version: 'aes128gcm',
  privateKey: ua,
  authSecret: b64(authSecret),
});
if (back.toString() !== plaintext) throw new Error('http_ece did not round-trip');

// And the VAPID half: the deterministic segments of the JWT.
const vapid = webpush.generateVAPIDKeys();
const endpoint = 'https://fcm.googleapis.com/fcm/send/abcdef-0123456789';
const exp = 1786780000 + 12 * 60 * 60;
const headers = webpush.getVapidHeaders(
  new URL(endpoint).origin,
  // Recorded, not configuration. This address is baked into the
  // expected VAPID header further down — a base64 payload captured from
  // the reference `web-push` library — so changing it here without
  // regenerating that string makes the vector disagree with itself.
  //
  // It deliberately keeps `iakauntan.my` after the rest of the project
  // moved to .com. A vector is a snapshot of what another
  // implementation produced on a particular day; sweeping a rename
  // through it edits the evidence rather than the code, and the
  // assertion it feeds stops being a cross-check against anything.
  'mailto:support@iakauntan.my',
  vapid.publicKey,
  vapid.privateKey,
  'aes128gcm',
  exp,
);

console.log(JSON.stringify({
  note: 'Generated by supabase/functions/_shared/web_push_vector.js against '
    + 'http_ece and web-push, the reference implementations. Regenerate with '
    + 'node vector.js if the format ever changes.',
  subscription: {
    endpoint,
    p256dh: b64(ua.getPublicKey()),
    auth: b64(authSecret),
  },
  receiverPrivateKey: b64(ua.getPrivateKey()),
  sender: {
    publicKey: b64(as.getPublicKey()),
    privateKey: b64(as.getPrivateKey()),
  },
  salt: b64(salt),
  plaintext,
  body: b64(body),
  vapid: {
    publicKey: vapid.publicKey,
    privateKey: vapid.privateKey,
    subject: 'mailto:support@iakauntan.my',
    expiry: exp,
    authorization: headers.Authorization,
  },
}, null, 2));
