"""Build the Play Store asset set.

    python3 brand/store/build.py [outdir]

Emits, into `outdir` (default `brand/store/out`):

    01-feature-graphic/          1 x 1024x500
    02-phone/                    8 x 1080x1920   (9:16)
    03-tablet-7in/               8 x 1920x1080   (16:9)
    04-tablet-10in/              8 x 2560x1440   (16:9)
    05-screenshots-min-1080px/   8 x 3840x2160   (16:9)
    06-screenshots-min-720px/    8 x 1280x720    (16:9)
    99-all-screens-phone/       97 x 1080x1920   (every screen in the catalogue)

and zips the lot.
"""
import os, shutil, sys, zipfile
import catalogue, specs, shot, featured

HERO = ['/dashboard', '/sales/invoice', '/einvoice', '/hr/payroll',
        '/reports', '/ask', '/crm', '/till']

SETS = [
    ('02-phone', 'phone', (1080, 1920), 'Phone'),
    ('03-tablet-7in', 'tablet7', (1920, 1080), '7-inch tablet'),
    ('04-tablet-10in', 'tablet10', (2560, 1440), '10-inch tablet'),
    ('05-screenshots-min-1080px', 'tablet4k', (3840, 2160), 'Min side 1,080px'),
    ('06-screenshots-min-720px', 'tablet720', (1280, 720), 'Min side 720px'),
]

README = """iAkauntan — Google Play store assets
===================================

Generated by brand/store/build.py. Regenerate with:

    python3 brand/store/build.py

01-feature-graphic/        1024 x 500 PNG.  Play's feature graphic slot.
02-phone/                  1080 x 1920 (9:16), 8 shots.
03-tablet-7in/             1920 x 1080 (16:9), 8 shots.
04-tablet-10in/            2560 x 1440 (16:9), 8 shots.
05-screenshots-min-1080px/ 3840 x 2160 (16:9), 8 shots — for the slot whose
                           sides must be 1,080-7,680px and files under 8 MB.
06-screenshots-min-720px/  1280 x 720 (16:9), 8 shots — for the slot whose
                           sides must be 720-7,680px and files under 15 MB.
99-all-screens-phone/      Every screen in the app's own screen catalogue,
                           97 of them, at phone size. Not for upload as-is;
                           it is the pool to pick a different eight from.

Every file is PNG, well inside each slot's size limit. The eight are the
same eight in every set, laid out for the form factor: phone shots have
the bottom navigation bar the app shows on a phone, tablet shots have the
navigation rail and the list-plus-detail split the app shows on a tablet.

WHAT THESE IMAGES ARE
---------------------
They are rendered mockups, drawn by this repository's own code in the
app's own theme -- the colours and the type come from
app/lib/src/core/theme.dart, the mark from brand/mark.py, and the screen
names and routes are parsed out of
app/lib/src/features/feedback/screen_catalogue.dart, which the app's own
test suite already asserts against the router. They are not captures of a
running build: this machine has no Flutter toolchain and no reachable
Supabase, which is the same wall app/screenshots/*.dart documents.

The figures on them are invented. No real company's books appear here.

Google Play requires store screenshots to represent the actual in-app
experience. Before publishing, either capture the same eight screens from
a real build and swap them in, or satisfy yourself that each of these
matches what the app now shows. The feature graphic is marketing artwork
and has no such constraint.
"""


def slug(route):
    return route.strip('/').replace('/', '-') or 'home'


def main(outdir):
    cat = {r: (m, a, l) for m, a, l, r in catalogue.screens()}
    missing = [r for r in HERO if r not in cat]
    if missing:
        raise SystemExit(f'not in the catalogue any more: {missing}')
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)

    fg = os.path.join(outdir, '01-feature-graphic')
    os.makedirs(fg)
    featured.build(os.path.join(fg, 'feature-graphic-1024x500.png'))
    print('feature graphic')

    for folder, profile, size, label in SETS:
        path = os.path.join(outdir, folder)
        os.makedirs(path)
        for i, route in enumerate(HERO, 1):
            m, a, l = cat[route]
            img = shot.render(specs.build(m, a, l, route), profile)
            assert img.size == size, (folder, img.size, size)
            img.save(os.path.join(path, f'{i:02d}-{slug(route)}.png'), 'PNG',
                     optimize=True)
        print(f'{folder}: 8 x {size[0]}x{size[1]}')

    allp = os.path.join(outdir, '99-all-screens-phone')
    os.makedirs(allp)
    for i, (m, a, l, route) in enumerate(catalogue.screens(), 1):
        img = shot.render(specs.build(m, a, l, route), 'phone')
        img.save(os.path.join(allp, f'{i:03d}-{slug(route)}.png'), 'PNG', optimize=True)
    print(f'99-all-screens-phone: {i} x 1080x1920')

    open(os.path.join(outdir, 'README.txt'), 'w').write(README)

    zpath = outdir.rstrip('/') + '.zip'
    with zipfile.ZipFile(zpath, 'w', zipfile.ZIP_DEFLATED) as z:
        for root, _, files in os.walk(outdir):
            for name in sorted(files):
                full = os.path.join(root, name)
                z.write(full, os.path.join('iakauntan-play-assets',
                                           os.path.relpath(full, outdir)))
    print('zip:', zpath, f'{os.path.getsize(zpath) / 1e6:.1f} MB')
    return zpath


if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, 'out'))
