"""Build a store's asset set.

    python3 brand/store/build.py              # Google Play -> out/, out.zip
    python3 brand/store/build.py --ios        # App Store   -> out-ios/, out-ios.zip
    python3 brand/store/build.py --ios DIR    # ... somewhere else

Google Play (`out/`):

    01-feature-graphic/          1 x 1024x500
    02-phone/                    8 x 1080x1920   (9:16)
    03-tablet-7in/               8 x 1920x1080   (16:9)
    04-tablet-10in/              8 x 2560x1440   (16:9)
    05-screenshots-min-1080px/   8 x 3840x2160   (16:9)
    06-screenshots-min-720px/    8 x 1280x720    (16:9)
    99-all-screens-phone/       97 x 1080x1920   (every screen in the catalogue)

App Store (`out-ios/`):

    01-iphone-6.5in/            10 x 1284x2778  (portrait)
    02-ipad-12.9in-portrait/    10 x 2048x2732
    03-ipad-12.9in-landscape/   10 x 2732x2048
"""
import os, shutil, sys, zipfile
import catalogue, specs, shot, featured

HERO = ['/dashboard', '/sales/invoice', '/einvoice', '/hr/payroll',
        '/reports', '/ask', '/crm', '/till']

# The App Store slots take ten. The two extra carry the modules the eight
# leave out: what a company owes, and what SSM is waiting for.
HERO_IOS = HERO + ['/purchases/bill', '/secretarial']

PLAY_SETS = [
    ('02-phone', 'phone', (1080, 1920)),
    ('03-tablet-7in', 'tablet7', (1920, 1080)),
    ('04-tablet-10in', 'tablet10', (2560, 1440)),
    ('05-screenshots-min-1080px', 'tablet4k', (3840, 2160)),
    ('06-screenshots-min-720px', 'tablet720', (1280, 720)),
]

IOS_SETS = [
    ('01-iphone-6.5in', 'ios_phone', (1284, 2778)),
    ('02-ipad-12.9in-portrait', 'ios_ipad', (2048, 2732)),
    ('03-ipad-12.9in-landscape', 'ios_ipad_l', (2732, 2048)),
]

MOCKUP_NOTE = """WHAT THESE IMAGES ARE
---------------------
They are rendered mockups, drawn by this repository's own code in the
app's own theme -- the colours and the type come from
app/lib/src/core/theme.dart, the mark from brand/mark.py, and the screen
names and routes are parsed out of
app/lib/src/features/feedback/screen_catalogue.dart, which the app's own
test suite already asserts against the router. They are not captures of a
running build: this machine has no Flutter toolchain and no reachable
Supabase, which is the same wall app/screenshots/*.dart documents.

The figures on them are invented. No real company's books appear here.
"""

PLAY_README = """iAkauntan — Google Play store assets
===================================

Generated by brand/store/build.py. Regenerate with:

    python3 brand/store/build.py

01-feature-graphic/        1024 x 500 PNG.  Play's feature graphic slot.
02-phone/                  1080 x 1920 (9:16), 8 shots.
03-tablet-7in/             1920 x 1080 (16:9), 8 shots.
04-tablet-10in/            2560 x 1440 (16:9), 8 shots.
05-screenshots-min-1080px/ 3840 x 2160 (16:9), 8 shots — for the slot whose
                           sides must be 1,080-7,680px and files under 8 MB.
06-screenshots-min-720px/  1280 x 720 (16:9), 8 shots — for the slot whose
                           sides must be 720-7,680px and files under 15 MB.
99-all-screens-phone/      Every screen in the app's own screen catalogue,
                           97 of them, at phone size. Not for upload as-is;
                           it is the pool to pick a different eight from.

Every file is PNG, well inside each slot's size limit. The eight are the
same eight in every set, laid out for the form factor: phone shots have
the bottom navigation bar the app shows on a phone, tablet shots have the
navigation rail and the list-plus-detail split the app shows on a tablet.

%s
Google Play requires store screenshots to represent the actual in-app
experience. Before publishing, either capture the same eight screens from
a real build and swap them in, or satisfy yourself that each of these
matches what the app now shows. The feature graphic is marketing artwork
and has no such constraint.
""" % MOCKUP_NOTE

IOS_README = """iAkauntan — Apple App Store screenshots
======================================

Generated by brand/store/build.py. Regenerate with:

    python3 brand/store/build.py --ios

01-iphone-6.5in/          1284 x 2778 portrait, 10 shots. The 6.5-inch
                          iPhone slot, which also serves 6.1-inch and
                          smaller devices when no other set is uploaded.
02-ipad-12.9in-portrait/  2048 x 2732, 10 shots.
03-ipad-12.9in-landscape/ 2732 x 2048, the same ten in landscape. Upload
                          one iPad set or the other, not both -- the pair
                          is here so the orientation is your choice.

All PNG, RGB, no alpha channel: App Store Connect rejects a screenshot
that carries one.

The ten are the same ten everywhere, laid out for the device. The iPhone
shots have the bottom navigation bar and the iPad shots the navigation
rail and the list-plus-detail split, because that is what app_shell.dart
builds at each width. What differs from the Play set is only what iOS
draws itself: the status bar and the home indicator.

1  Dashboard          6  Ask about your books
2  Invoices           7  CRM pipeline
3  e-Invoice (LHDN)   8  Point of sale
4  Payroll            9  Bills
5  Reports           10  Company secretarial

%s
Apple requires screenshots to show the app in use. Before submitting,
either capture these ten from a real build on an iPhone 6.5-inch and an
iPad Pro 12.9-inch simulator and swap them in, or satisfy yourself that
each of these matches what the app now shows.
""" % MOCKUP_NOTE

STORES = {
    'play': dict(out='out', sets=PLAY_SETS, heroes=HERO, readme=PLAY_README,
                 zip_root='iakauntan-play-assets', feature=True, pool=True),
    'ios': dict(out='out-ios', sets=IOS_SETS, heroes=HERO_IOS, readme=IOS_README,
                zip_root='iakauntan-app-store-assets', feature=False, pool=False),
}


def slug(route):
    return route.strip('/').replace('/', '-') or 'home'


def main(outdir, store='play'):
    s = STORES[store]
    cat = {r: (m, a, l) for m, a, l, r in catalogue.screens()}
    missing = [r for r in s['heroes'] if r not in cat]
    if missing:
        raise SystemExit(f'not in the catalogue any more: {missing}')
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)

    if s['feature']:
        fg = os.path.join(outdir, '01-feature-graphic')
        os.makedirs(fg)
        featured.build(os.path.join(fg, 'feature-graphic-1024x500.png'))
        print('feature graphic')

    for folder, profile, size in s['sets']:
        path = os.path.join(outdir, folder)
        os.makedirs(path)
        for i, route in enumerate(s['heroes'], 1):
            m, a, l = cat[route]
            img = shot.render(specs.build(m, a, l, route), profile)
            assert img.size == size, (folder, img.size, size)
            img.save(os.path.join(path, f'{i:02d}-{slug(route)}.png'), 'PNG',
                     optimize=True)
        print(f'{folder}: {len(s["heroes"])} x {size[0]}x{size[1]}')

    if s['pool']:
        allp = os.path.join(outdir, '99-all-screens-phone')
        os.makedirs(allp)
        for i, (m, a, l, route) in enumerate(catalogue.screens(), 1):
            img = shot.render(specs.build(m, a, l, route), 'phone')
            img.save(os.path.join(allp, f'{i:03d}-{slug(route)}.png'), 'PNG',
                     optimize=True)
        print(f'99-all-screens-phone: {i} x 1080x1920')

    open(os.path.join(outdir, 'README.txt'), 'w').write(s['readme'])

    zpath = outdir.rstrip('/') + '.zip'
    with zipfile.ZipFile(zpath, 'w', zipfile.ZIP_DEFLATED) as z:
        for root, _, files in os.walk(outdir):
            for name in sorted(files):
                full = os.path.join(root, name)
                z.write(full, os.path.join(s['zip_root'],
                                           os.path.relpath(full, outdir)))
    print('zip:', zpath, f'{os.path.getsize(zpath) / 1e6:.1f} MB')
    return zpath


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    store = 'ios' if '--ios' in sys.argv[1:] else 'play'
    here = os.path.dirname(os.path.abspath(__file__))
    main(args[0] if args else os.path.join(here, STORES[store]['out']), store)
