/**
 * A room, and the people in it.
 *
 * A room here is a `room_name` from `public.chat_calls` — sixteen random
 * bytes, generated by Postgres when somebody pressed the call button. It
 * is not created by an API call and nothing announces it: the first
 * valid token bearing that name brings it into existence, and it is
 * destroyed when the last person leaves. There is no room list, no room
 * registry to keep in step with the database, and nothing to clean up
 * when a call is abandoned.
 *
 * That is deliberate. The database is the application, and it already
 * knows who is in a call. Anything this server remembered about a call
 * would be a second copy of that, free to disagree with it.
 */

/** One person, one socket. */
export class Peer {
  /**
   * @param {{ id: string, displayName: string, send: (frame: object) => void }} options
   */
  constructor({ id, displayName, send }) {
    this.id = id;
    this.displayName = displayName;
    this._send = send;

    /** Set by `join`. Until then this peer receives nothing. */
    this.rtpCapabilities = null;
    this.joined = false;
    this.closed = false;

    /** @type {Map<string, import('mediasoup').types.WebRtcTransport>} */
    this.transports = new Map();
    /** @type {Map<string, import('mediasoup').types.Producer>} */
    this.producers = new Map();
    /** @type {Map<string, import('mediasoup').types.Consumer>} */
    this.consumers = new Map();

    this.sendTransportId = null;
    this.recvTransportId = null;
  }

  notify(notification, data) {
    if (this.closed) return;
    this._send({ notification, data });
  }

  get recvTransport() {
    return this.recvTransportId
      ? this.transports.get(this.recvTransportId)
      : undefined;
  }

  get sendTransport() {
    return this.sendTransportId
      ? this.transports.get(this.sendTransportId)
      : undefined;
  }

  summary() {
    return { id: this.id, displayName: this.displayName };
  }

  close() {
    if (this.closed) return;
    this.closed = true;
    // Closing a transport closes every producer and consumer on it, and
    // mediasoup fires `transportclose` on each — so this is the whole
    // teardown, not the start of one.
    for (const transport of this.transports.values()) transport.close();
    this.transports.clear();
    this.producers.clear();
    this.consumers.clear();
  }
}

export class Room {
  /**
   * @param {{ id: string, router: import('mediasoup').types.Router, config: object, onEmpty?: (id: string) => void }} options
   */
  constructor({ id, router, config, onEmpty }) {
    this.id = id;
    this.router = router;
    this.config = config;
    this.onEmpty = onEmpty;
    /** @type {Map<string, Peer>} */
    this.peers = new Map();
    this.closed = false;
  }

  get isFull() {
    return this.peers.size >= this.config.maxPeersPerRoom;
  }

  addPeer(peer) {
    // One socket per person. A second one is not a second participant —
    // it is the same person on a reconnect the server has not noticed
    // yet, or on a second device. Either way the older socket is stale,
    // so it goes rather than sitting in the room as somebody nobody can
    // hear.
    //
    // The new peer goes into the map *before* the old one is closed, and
    // that order is the whole point: closing the only peer in a room
    // empties it, and an empty room closes its router. Done the other
    // way round, somebody reconnecting into a room they were alone in
    // would be admitted to a room that had just been destroyed.
    //
    // No `peerClosed` goes out either. As far as everybody else is
    // concerned that person has not left — their consumers of the old
    // socket's producers are closed by mediasoup, which is exactly the
    // `consumerClosed` a reconnect should look like.
    const existing = this.peers.get(peer.id);
    this.peers.set(peer.id, peer);
    if (existing) existing.close();
  }

  /** Everybody except this one, and only those who have joined. */
  others(peer) {
    return [...this.peers.values()].filter((p) => p !== peer && p.joined);
  }

  broadcast(from, notification, data) {
    for (const peer of this.others(from)) peer.notify(notification, data);
  }

  async createWebRtcTransport(peer, { producing, consuming }) {
    const transport = await this.router.createWebRtcTransport({
      listenInfos: this.config.listenInfos,
      enableUdp: true,
      enableTcp: true,
      preferUdp: true,
      initialAvailableOutgoingBitrate:
        this.config.initialAvailableOutgoingBitrate,
      appData: { peerId: peer.id, producing, consuming },
    });

    // A transport whose ICE gives up is a peer who has left, whatever
    // the socket still says. Without this the room keeps a ghost with a
    // camera light on.
    transport.on('dtlsstatechange', (state) => {
      if (state === 'failed' || state === 'closed') transport.close();
    });

    peer.transports.set(transport.id, transport);
    if (producing) peer.sendTransportId = transport.id;
    if (consuming) peer.recvTransportId = transport.id;

    return {
      id: transport.id,
      iceParameters: transport.iceParameters,
      iceCandidates: transport.iceCandidates,
      dtlsParameters: transport.dtlsParameters,
    };
  }

  /**
   * Puts a peer in the room properly: from here they are visible to
   * everybody else and start receiving what is already being sent.
   */
  async join(peer, { rtpCapabilities, displayName }) {
    if (peer.joined) throw new Error('Already joined');
    peer.rtpCapabilities = rtpCapabilities;
    if (typeof displayName === 'string' && displayName.length > 0) {
      // Only as a label. Identity is the token's `sub`, which a client
      // cannot choose — see `token.js`.
      peer.displayName = displayName;
    }
    peer.joined = true;

    const others = this.others(peer);
    // `peerId`, not `id`. The join *response* lists peers as `{ id,
    // displayName }` and this notification names the same thing
    // `peerId`, which looks like an inconsistency and is the contract in
    // `docs/call-signalling.md` — and the contract is what the Flutter
    // client reads. Emitting `id` here left every `peerJoined` silently
    // ignored by the app: the caller sat alone on screen until the other
    // person's first track happened to arrive.
    this.broadcast(peer, 'peerJoined', {
      peerId: peer.id,
      displayName: peer.displayName,
    });

    // Everything already in flight, in the order it was produced. Doing
    // this after `joined` is set means a producer appearing *during*
    // this loop is fanned out by `produce` as well — a duplicate
    // `newConsumer` for the same producer is not possible because
    // `consume` is keyed on the producer and mediasoup would refuse the
    // second one, but a *missing* one would be a silent participant.
    for (const other of others) {
      for (const producer of other.producers.values()) {
        await this.consume(peer, other, producer);
      }
    }

    return { peers: others.map((p) => p.summary()) };
  }

  /** Whoever is sharing their screen, if anybody. */
  screenSharer() {
    for (const peer of this.peers.values()) {
      for (const producer of peer.producers.values()) {
        if (producer.appData.source === 'screen') return peer;
      }
    }
    return null;
  }

  async produce(peer, { transportId, kind, rtpParameters, appData }) {
    const transport = peer.transports.get(transportId);
    if (!transport) throw new Error('No such transport');
    if (transport.appData.producing !== true) {
      throw new Error('That transport does not send');
    }

    const source = appData?.source ?? kind;

    // One screen at a time. Not a technical limit — mediasoup would
    // carry four — but a screen share takes over the far side's window,
    // and two of them at once means two people fighting over everybody
    // else's display with no way to choose. Refused here rather than in
    // the app, because "the app will not let you" is not a rule.
    if (source === 'screen') {
      const sharer = this.screenSharer();
      if (sharer && sharer !== peer) {
        throw new Error(`${sharer.displayName} is already sharing a screen`);
      }
      if (sharer === peer) {
        throw new Error('You are already sharing a screen');
      }
    }

    const producer = await transport.produce({
      kind,
      rtpParameters,
      // `source` is what tells a camera track from a microphone one on
      // the far side — and now a screen from a camera, both of which
      // are `kind: 'video'`. Taken from the client because only the
      // client knows, and harmless if it lies about mic versus cam: it
      // is a label on a stream that peer is already entitled to send.
      // `screen` is the exception, because it claims a shared resource,
      // which is why the check above is here and not in the app.
      appData: { peerId: peer.id, source },
    });

    peer.producers.set(producer.id, producer);

    producer.on('transportclose', () => {
      peer.producers.delete(producer.id);
    });

    for (const other of this.others(peer)) {
      await this.consume(other, peer, producer);
    }

    return { id: producer.id };
  }

  /**
   * Gives `consumerPeer` a stream of `producer`.
   *
   * Refusals here are ordinary and are not errors: a peer whose device
   * cannot decode this codec, or who has not finished joining, simply
   * does not get a consumer. Throwing would fail the *producer's*
   * request because somebody else's browser is old.
   */
  async consume(consumerPeer, producerPeer, producer) {
    if (!consumerPeer.joined || consumerPeer.closed) return null;
    const transport = consumerPeer.recvTransport;
    if (!transport) return null;
    if (
      !this.router.canConsume({
        producerId: producer.id,
        rtpCapabilities: consumerPeer.rtpCapabilities,
      })
    ) {
      return null;
    }

    const consumer = await transport.consume({
      producerId: producer.id,
      rtpCapabilities: consumerPeer.rtpCapabilities,
      // Paused, always. mediasoup's own advice: an unpaused consumer
      // gets a key frame thrown at it before the client has a receiver
      // for it, and the client shows a black rectangle for as long as it
      // takes the next one to arrive. The client sends `resumeConsumer`
      // the moment it has somewhere to put it.
      paused: true,
      appData: { peerId: producerPeer.id, source: producer.appData.source },
    });

    consumerPeer.consumers.set(consumer.id, consumer);

    consumer.on('transportclose', () => {
      consumerPeer.consumers.delete(consumer.id);
    });
    consumer.on('producerclose', () => {
      consumerPeer.consumers.delete(consumer.id);
      consumerPeer.notify('consumerClosed', { consumerId: consumer.id });
    });
    consumer.on('producerpause', () =>
      consumerPeer.notify('consumerPaused', { consumerId: consumer.id }),
    );
    consumer.on('producerresume', () =>
      consumerPeer.notify('consumerResumed', { consumerId: consumer.id }),
    );

    consumerPeer.notify('newConsumer', {
      peerId: producerPeer.id,
      producerId: producer.id,
      id: consumer.id,
      kind: consumer.kind,
      rtpParameters: consumer.rtpParameters,
      appData: consumer.appData,
      producerPaused: consumer.producerPaused,
    });

    return consumer;
  }

  removePeer(peer) {
    if (!this.peers.has(peer.id) || this.peers.get(peer.id) !== peer) {
      // Already replaced by a newer socket for the same person. Close
      // this one's media but do not tell the room somebody left, because
      // as far as the room is concerned nobody has.
      peer.close();
      return;
    }

    this.peers.delete(peer.id);
    peer.close();

    if (peer.joined) {
      for (const other of this.peers.values()) {
        if (other.joined) other.notify('peerClosed', { peerId: peer.id });
      }
    }

    if (this.peers.size === 0) this.close();
  }

  close() {
    if (this.closed) return;
    this.closed = true;
    for (const peer of this.peers.values()) peer.close();
    this.peers.clear();
    this.router.close();
    this.onEmpty?.(this.id);
  }
}
