#!/usr/bin/env python3
"""Every column is written by something and read by something.

    python3 scripts/check_orphan_columns.py

The sweep this branch keeps finding things with, made a gate so it stops
depending on somebody running it.

`check_unreachable.py` asks the same question one layer up -- a
repository method or a provider that nothing reaches -- and its own
header says why a procedure nobody remembers is a procedure that fails
silently. This asks it of the SCHEMA, which on a project whose first
rule is that the database IS the application is the layer that matters
most.

## What it found, before it was a gate

Twenty columns that nothing at all mentions: no function, no view, no
constraint, no index, no Dart, no edge function, no assertion. Two were
capabilities the product could not reach:

  * `tax_codes.is_inclusive` -- a column since `0003`.
    `app.calc_document_line` could always compute a tax-inclusive line
    and nothing ever set the flag, so NO DOCUMENT in this product could
    be raised at a price that includes its tax. `0641`.

  * `organizations.tourism_tax_reg_no` -- a column since `0001`, on the
    line after `sst_registration_no`. Its neighbour is asked for at
    onboarding, edited in settings, printed on every PDF, shown to the
    customer and sent to LHDN. This one had no form, no print and no
    payload, so an operator registered under the Tourism Tax Act had
    nowhere to record the number RMCD issued. `0642`.

The rest are below, each with the reason it stays -- which is the whole
point of the file. A column that nothing uses is either a missing
feature or a decision, and the difference has to be written down or the
next person surveys all twenty again.

## What it cannot see, which is worth knowing before trusting it

A column its own later migration names, and nothing else. Add a column
in `0700`, write a function in `0700` that reads it, and never let the
app near it: this passes. That is not a bug to fix by narrowing the
rule -- a schema-only feature is a legitimate thing, and
`check_unreachable.py` is the sweep that asks whether the APP reaches
something.

Concretely: revert the Dart half of `0642` and this still passes,
because `0642` itself names `tourism_tax_reg_no`. Proved, not assumed,
and `check_orphan_columns_test.py` carries a named assertion for each
of the two columns this sweep found so that a revert is caught by
something.

So the question this answers is "has anybody thought about this column
since the day it was typed", and the answer is worth a gate: twenty
columns had nothing at all, and two of them were features the product
could not reach.

## How it reads the schema

From `docs/api/openapi.json`, not from a database. That file is
generated by `scripts/generate_api_description.py` and CI already
refuses a commit where it disagrees with the schema, so it is the
schema -- and reading it means this gate needs no Postgres and can run
in the cheap job.

## What counts as a mention

The column name appearing anywhere outside the statement that creates
it: another migration, a test, Dart, an edge function, a doc. That is
deliberately generous. A name that appears in a `select` is read; a name
that appears in a comment is at least ACKNOWLEDGED, and the failure this
looks for is the column nobody has thought about since the day it was
typed.

Comments are stripped from the file that DECLARES the column only --
otherwise `0001`'s own commentary would clear half of its own table.
"""
import collections
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = ROOT / 'docs' / 'api' / 'openapi.json'

# Columns that nothing uses, and stay that way on purpose. The reason is
# the entry; a column named here without one is not an exemption, it is
# a column somebody hid.
#
# A ratchet, in the shape `check_blind_catches.py` and
# `check_unreachable.py` use: the number should go DOWN. Adding a name
# is an argument made in writing, here, next to the ones below.
DELIBERATE: dict[str, str] = {
    # A company registered with SSM shall have a registered office IN
    # MALAYSIA -- Companies Act 2016 s.46 -- so this can only ever hold
    # its default. The registered ADDRESS is editable on the company
    # form, lines and postcode and city and state; a country beside
    # them would offer a choice that does not exist, and any answer but
    # MYS is a company that cannot be registered here at all.
    'organizations.registered_country_code':
        'a registered office is in Malaysia by statute; the default is '
        'the only answer',

    # Written by its own default on every insert, so it is not an
    # unwritten column -- it is an unREAD one. It records when a name
    # went on the reserved list, which is worth having in the row and
    # is not worth a screen: the console lists the names, and nobody
    # has asked when one was added.
    'reserved_names.added_at':
        'its own default writes it; nothing needs to read when a name '
        'was reserved',

    # `0171`'s header says what it is for, under a heading that calls
    # it deliberate: the MBRS taxonomy is versioned and changes between
    # releases, and the mapping "must be reconciled against the mTool
    # taxonomy in use before the first live lodgement, and
    # `taxonomy_version` is there to record which one".
    #
    # Unwritten because the answer is not knowable here: it is a real
    # mTool release in somebody's hands. Writing a guess would be worse
    # than null -- a filing claiming to have been reconciled against a
    # taxonomy nobody checked. Same shape as the two passkey
    # association files.
    'mbrs_elements.taxonomy_version':
        '0171 keeps it for the mTool release a mapping was reconciled '
        'against, which is not knowable from here',
}

# The vestigial half of a mechanism something else now does properly.
# Not "leave it alone for ever" -- a finding, with what closing it
# needs, recorded where the next person will look.
SUPERSEDED: dict[str, str] = {
    # `import_opening_balances` is the reachable way to open a set of
    # books, and it does the right thing: a GL entry dated `p_as_at`
    # with `source = 'opening_balance'`. The DATE of an opening balance
    # is on that journal.
    #
    # The trap, and why this is written down rather than dropped:
    # `accounts.opening_balance` is still READ -- by
    # `report_trial_balance`, `report_general_ledger`,
    # `report_balance_sheet`, `report_cash_flow`,
    # `report_changes_in_equity` and `report_group_trial_balance` --
    # and read DATELESS, added into the opening figure of whatever
    # period was asked for. Nothing in the app writes it; the demo
    # seeds do. So the trap is latent: the first company to set it gets
    # its opening balance in every comparative period, including
    # periods before it converted.
    #
    # To close: the demo seeds post a dated opening journal like
    # everything else, and then those six reports stop reading the
    # column. A change to six statutory reports, and its own commit.
    'accounts.opening_balance_date':
        'superseded by import_opening_balances, which dates its '
        'journal; see the dateless read this leaves behind',

    # `0548` computes this rather than storing it: a promotion carries
    # `trial_days`, and `app.plan_price_on` decides whether a day falls
    # inside the trial from `p_started + p.trial_days`. A per-org
    # timestamp is the older idea, and two places holding when a trial
    # ends is one too many -- the stored one goes stale the moment a
    # promotion changes. `0018`'s platform setting `trial_days` is the
    # same story a layer up, and 0548 is where it got applied.
    #
    # To close: drop the column. Nothing reads it.
    'organizations.trial_ends_at':
        'superseded by 0548, which computes a trial from the promotion '
        'instead of storing its end',

    # The attachments module is how a file reaches a row here:
    # `attachments (entity_table, entity_id, storage_path)`, with its
    # lifecycle asserted in `attachment_lifecycle.sql` and the claim
    # case in `claim_attachments.sql` -- which attaches a receipt to
    # `expense_claims` through that table and nowhere near these two.
    #
    # A path column is the older and worse idea: one file per row, no
    # name, size or type, and nothing to clean it up when the row goes.
    #
    # To close: drop them, in a migration sure no deployment ever wrote
    # one.
    'expense_claim_lines.receipt_path':
        'the attachments module carries a claim\'s files',
    'expenses.receipt_url':
        'the attachments module carries an expense\'s files',
}

# The column is not the finding -- the TABLE is. Reporting the column
# sends the next person to the wrong question.
WHOLE_TABLE_UNREACHED: dict[str, str] = {
    # `public.notes`: free-form notes attachable to anything, on the
    # `entity_table`/`entity_id` shape `attachments` uses. The
    # attachments half was built; this half never was. No function and
    # no Dart touches the table.
    #
    # Whether it SHOULD be built has a real answer on both sides:
    # `activities` already carries a CRM timeline, and a good many
    # tables carry their own `notes` text column. Pinning a note is not
    # a feature until there are notes.
    'notes.is_pinned': 'nothing reaches public.notes at all',

    # `public.fs_disclosures`: one row per MBRS disclosure code on a
    # financial-statements filing. No function reads or writes the
    # table and no Dart mentions it, while `fs_filings` beside it IS
    # reached -- so this is the part of MBRS that was tabled and never
    # built.
    'fs_disclosures.value_text':
        'nothing reaches public.fs_disclosures at all',
}

# GAPS. Not exemptions -- a ratchet, in the shape `check_unreachable.py`
# uses for the providers nobody had drawn: "the number should go DOWN
# rather than up", and each of those four was closed rather than kept.
#
# Every entry is a capability the product cannot reach, named so that
# another cannot be added quietly. What closing it needs is written
# beside it, because the reason a gap stays open for months is that
# nobody remembers what closing it involved.
KNOWN_GAPS: dict[str, str] = {
    # A failed e-Invoice is retried for ever, because nothing counts
    # the attempts.
    #
    # `submit.ts` and `consolidations.ts` write `last_attempt_at` at
    # every failure site and never touch `retry_count`. `0007` indexes
    # `(org_id, status, last_attempt_at)`, which is the retry picker --
    # so a document that can never succeed (a malformed buyer TIN, a
    # rejection that will be rejected again) is re-submitted on every
    # sweep, with nothing able to give up on it, against an API that
    # is rate-limited and counts submissions.
    #
    # To close: increment it wherever `last_attempt_at` is written, and
    # have the picker stop at a ceiling -- leaving the document
    # visibly exhausted rather than silently dropped, because a
    # document nobody submits is an e-Invoice LHDN never received.
    'einvoice_documents.retry_count':
        'increment it where last_attempt_at is written, and stop the '
        'picker at a ceiling',

    # What was SENT to MyInvois. `response_payload` beside it IS
    # written, so a rejected submission records the rejection and not
    # the document that caused it -- the one thing anybody wants when
    # LHDN refuses a document and the message is a code.
    #
    # To close: the submit path writes it on the insert that already
    # writes `response_payload`, and the e-Invoice log offers it where
    # somebody can read it. Size is the thing to decide: a submission
    # carries up to a hundred signed documents, so this may want the
    # envelope and per-document metadata rather than every base64 body.
    'einvoice_submissions.request_payload':
        'the myinvois submit path writes it beside response_payload, '
        'and the log screen shows it',

    # Where SSM correspondence goes. The corporate secretarial module
    # tracks an entity's registered office, its business address and
    # its phone, and each of those is on the entity form -- this one
    # was declared beside them in `0061` and never asked for. A
    # secretary keeps it in the engagement letter, where the product
    # cannot see it.
    #
    # To close: a field on the corp entity editor and the column in its
    # update path. No migration: the column is there and the policy
    # already lets a secretary write the row.
    'corp_entities.correspondence_email':
        'a field on the corp entity editor, and the column in its '
        'update path',

    # An employee's passport scan, permit or certificate. The Documents
    # section of the employee record tracks the TITLE, the type and the
    # expiry of each, and offers no way to attach the document -- so
    # what expires is recorded and what expires is not held.
    #
    # To close: that section attaches through the attachments module
    # like everything else in this product
    # (`entity_table = 'employee_documents'`), which makes this column
    # superseded rather than missing; or it is used directly.
    'employee_documents.file_path':
        'the Documents section of the employee record holds no '
        'document; attach through the attachments module',
}

EXEMPT = {**DELIBERATE, **SUPERSEDED, **WHOLE_TABLE_UNREACHED, **KNOWN_GAPS}

# Where a column could actually be USED: the SQL that is the
# application, the assertions over it, the edge functions, and the
# client.
#
# `docs` and `scripts` are deliberately NOT here, and leaving them in
# is how the first version of this gate passed while exempting nothing.
#
#   * `scripts` holds THIS FILE, whose exemption lists name every
#     column they clear as a string literal. So naming a column below
#     gave it a second mention and it would never have been reported
#     again -- an exemption list that silences the gate by existing.
#     Ten of the thirteen entries below were exempting nothing, and
#     three real orphans were hidden by prose elsewhere.
#
#   * `docs` would mean a column is reached because somebody wrote its
#     name in a markdown file. `docs/unreachable.md` describes this
#     sweep AND lists the columns it found, so the write-up of a
#     finding would clear the finding.
#
# The same trap as the comment-stripping below, one layer out, and the
# same one `scripts/check_web_plugin_registrant.py` and
# `scripts/check_android_compile_sdk.py` each fell into: a check that
# reads its own documentation as evidence.
SEARCHED = (
    ('supabase/migrations', '*.sql'),
    ('supabase/tests', '*.sql'),
    ('supabase/functions', '*.ts'),
    ('app/lib', '*.dart'),
    ('app/test', '*.dart'),
    ('app/tool', '*.dart'),
    ('cloudflare', '*.ts'),
)

# Columns every table has, which are read generically and would swamp
# the report.
UNIVERSAL = {'id', 'org_id', 'created_at', 'updated_at', 'deleted_at',
             'created_by', 'updated_by'}


def strip_sql_comments(text: str) -> str:
    """`--` to end of line, and `/* */`.

    Only ever applied to the file that DECLARES the column. This
    repository explains itself at length inside its migrations, so a
    column named in the paragraph above its own `create table` would
    clear itself -- which is the same trap
    `check_web_plugin_registrant.py` and
    `check_android_compile_sdk.py` each fell into once.
    """
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    return re.sub(r'--.*?$', '', text, flags=re.M)


WORD = re.compile(r'[A-Za-z_][A-Za-z0-9_]*')


def tokens(text: str) -> collections.Counter:
    """How many times each identifier-shaped word appears in a file.

    Indexed once per file rather than searched once per column. The
    first version ran a regex over the whole tree for each of the 6,800
    columns in the description and did not finish inside five minutes
    -- which for a gate is the same as not existing, because nobody
    leaves it in the pipeline.

    Counted rather than merely present, and that is not an
    optimisation. A column created and USED in the same migration --
    `pos_kitchen_tickets.ready_at`, set by a function written directly
    below its own `create table` -- appears in exactly one file, so a
    sweep over files reports it as reached by nothing. Ten of the first
    thirty-five reported were that.
    """
    return collections.Counter(WORD.findall(text))


def columns() -> dict[str, list[str]]:
    schemas = json.loads(API.read_text())['components']['schemas']
    return {table: list(body.get('properties', {}))
            for table, body in sorted(schemas.items())}


def corpus() -> list[tuple[Path, str]]:
    out = []
    for folder, glob in SEARCHED:
        base = ROOT / folder
        if not base.is_dir():
            continue
        for path in sorted(base.rglob(glob)):
            out.append((path, path.read_text(errors='replace')))
    return out


DECLARES = re.compile(
    r'\b(?:create table (?:if not exists )?|alter table (?:only )?)'
    r'(?:public\.)?([a-z_][a-z0-9_]*)', re.I)


def declarers(files: list[tuple[Path, str]]) -> dict[str, set[int]]:
    """table -> the indexes of the files that create it or alter it.

    One pass over the tree, reading the table name OUT of each
    statement, rather than one pass per table looking for its name.

    Their prose does not count as a mention of their own columns;
    everything else in them does, because an `alter table` or a
    function body in the same file is a real use.
    """
    out: dict[str, set[int]] = {}
    for i, (_, text) in enumerate(files):
        for table in DECLARES.findall(text):
            out.setdefault(table.lower(), set()).add(i)
    return out


def main() -> int:
    if not API.is_file():
        print(f'no {API.relative_to(ROOT)} -- run '
              f'scripts/generate_api_description.py first', file=sys.stderr)
        return 2

    files = corpus()
    decl = declarers(files)

    # Indexed once. `full` is what a file says; `bare` is what it says
    # with its own commentary removed, and only consulted for the file
    # that declares the column in question.
    full = [tokens(text) for _, text in files]
    bare = [tokens(strip_sql_comments(text)) if path.suffix == '.sql' else tok
            for (path, text), tok in zip(files, full)]

    # token -> how many times it appears anywhere.
    seen: collections.Counter = collections.Counter()
    for tok in full:
        seen.update(tok)

    # Every column nothing mentions, WITHOUT the exemptions applied.
    # Applying them here is what made the "reached now" check below
    # report all thirteen: an exempted column never reached the list it
    # was being compared against, so every one of them looked wired up.
    unmentioned: set[str] = set()
    for table, cols in columns().items():
        here = decl.get(table.lower())
        if not here:
            # A view, or something the description carries that no
            # migration creates by that name. Not this gate's question.
            continue
        for col in cols:
            if col in UNIVERSAL:
                continue
            name = f'{table}.{col}'
            # Every mention anywhere, less the mentions the declaring
            # files make in their own prose.
            hits = seen.get(col, 0) - sum(
                full[i][col] - bare[i][col] for i in here)
            # One mention is the declaration itself. Two or more means
            # something names it -- in another file, or in a function
            # written below the `create table` in the same one.
            if hits <= 1:
                unmentioned.add(name)

    orphans = sorted(unmentioned - set(EXEMPT))

    if orphans:
        print('columns nothing writes and nothing reads:\n', file=sys.stderr)
        for name in orphans:
            print(f'  {name}', file=sys.stderr)
        print(f'\n{len(orphans)} orphan column(s). Each is a capability the '
              f'product cannot reach or a decision nobody wrote down.\n'
              f'Wire it up, or name it in this file WITH the reason: '
              f'DELIBERATE, SUPERSEDED, WHOLE_TABLE_UNREACHED, or '
              f'KNOWN_GAPS if it is a real gap somebody will close.',
              file=sys.stderr)
        return 1

    # Two ways an entry in this file rots, and both are quiet.
    #
    # The column is gone: the entry exempts nothing and nobody notices.
    # The same failure as a test that asserts about a screen somebody
    # deleted.
    known = {f'{table}.{col}' for table, cols in columns().items()
             for col in cols}
    stale = sorted(name for name in EXEMPT if name not in known)
    if stale:
        print('named in this file and no longer a column:\n', file=sys.stderr)
        for name in stale:
            print(f'  {name}', file=sys.stderr)
        print('\nRemove the entry. It is exempting nothing.', file=sys.stderr)
        return 1

    # Or the column is reached now -- somebody wired it up and left the
    # entry behind. Then the file reads as a list of what is missing
    # while describing something that is not, which is worse than
    # silence: the next person believes it.
    #
    # `reached` is every named column the sweep did NOT report, which
    # is only meaningful because the exemptions are no longer part of
    # the corpus -- see SEARCHED.
    reached = sorted(name for name in EXEMPT
                     if name in known and name not in unmentioned)
    if reached:
        print('named in this file and reached by something now:\n',
              file=sys.stderr)
        for name in reached:
            print(f'  {name}  -- {EXEMPT[name]}', file=sys.stderr)
        print('\nRemove the entry, and put the finding in '
              'docs/unreachable.md if it is worth keeping.', file=sys.stderr)
        return 1

    print(f'every column is mentioned by something '
          f'({len(DELIBERATE)} deliberate, {len(SUPERSEDED)} superseded, '
          f'{len(WHOLE_TABLE_UNREACHED)} on a table nothing reaches, '
          f'{len(KNOWN_GAPS)} known gap(s) still to close)')
    if KNOWN_GAPS:
        print('     still to close: ' + ', '.join(sorted(KNOWN_GAPS)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
