#!/usr/bin/env python3
"""Assertions for scripts/dependency_audit.py.

    python3 scripts/dependency_audit_test.py

The audit is the only thing in CI that looks at either dependency tree,
so its parsers are the kind of code that fails silently and reads as
good news. Three of them are worth pinning:

  * the import scanner, which must not mistake the `https://` literals
    in the edge functions' own test fixtures for dependencies -- there
    are two dozen of those, and a scanner that counted them would fail
    every run until somebody turned it off;
  * the pubspec.lock reader, which is hand-rolled because there is no
    YAML parser in the standard library and taking a dependency to read
    the dependency file is a joke that writes itself;
  * the OSV client, whose failure path has to RAISE. An advisory query
    that returns an empty list when the network is down reads exactly
    like a clean bill of health.
"""

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import dependency_audit as audit  # noqa: E402


def workspace(files: dict[str, str]) -> str:
    """A throwaway tree with supabase/functions in it."""
    root = tempfile.mkdtemp()
    for path, body in files.items():
        full = os.path.join(root, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, 'w', encoding='utf-8') as fh:
            fh.write(body)
    return root


class ImportScanner(unittest.TestCase):
    def test_finds_the_shapes_an_import_comes_in(self):
        root = workspace({'supabase/functions/a/index.ts': '''
import { createClient } from 'jsr:@supabase/supabase-js@2';
import 'npm:side-effect@1.0.0';
export { thing } from "jsr:@std/assert@1";
const lazy = await import('npm:lazy@3');
import { local } from './helpers.ts';
import { up } from '../_shared/util.ts';
'''})
        found = audit.deno_imports(root)
        self.assertEqual(
            sorted(found),
            ['jsr:@std/assert@1', 'jsr:@supabase/supabase-js@2',
             'npm:lazy@3', 'npm:side-effect@1.0.0'])
        # Relative imports are the function's own files, not dependencies.
        self.assertNotIn('./helpers.ts', found)
        self.assertNotIn('../_shared/util.ts', found)

    def test_a_url_in_a_fixture_is_not_a_dependency(self):
        # `supabase/functions` is full of these: webhook targets, push
        # endpoints, callback URLs under test. A scanner that treated a
        # string as an import would report two dozen findings a run.
        root = workspace({'supabase/functions/b/index_test.ts': '''
const endpoint = 'https://fcm.googleapis.com/fcm/send/abcdef';
const callback = "https://www.billplz.com/api/v3";
assertEquals(origin, 'https://sinar.iakauntan.com');
'''})
        self.assertEqual(audit.deno_imports(root), {})

    def test_remote_code_and_floating_versions_are_refused(self):
        root = workspace({'supabase/functions/c/index.ts': '''
import { a } from 'https://deno.land/std@0.100.0/http/mod.ts';
import { b } from 'jsr:@supabase/supabase-js';
'''})
        problems = audit.check_deno(root)
        joined = '\n'.join(problems)
        self.assertIn('Only jsr:, npm:, node:', joined)
        self.assertIn('with no version', joined)

    def test_a_new_dependency_has_to_be_declared(self):
        root = workspace({'supabase/functions/d/index.ts':
                          "import { z } from 'npm:zod@3.23.8';\n"})
        problems = audit.check_deno(root)
        # Named against the specifier. `any('DENO_CENSUS' in p)` alone
        # passed with the census check deleted: the two census entries
        # nothing imports produce messages carrying the same word, so
        # the assertion was answered by the wrong problem.
        self.assertTrue(
            any('zod' in p and 'DENO_CENSUS' in p for p in problems),
            problems)

    def test_a_census_entry_nothing_imports_is_a_problem(self):
        # The census going stale in the other direction: a dependency
        # removed from the code and left on the list reads as still in
        # use by anybody consulting it.
        root = workspace({'supabase/functions/e/index.ts':
                          "import { c } from 'jsr:@supabase/supabase-js@2';\n"})
        problems = audit.check_deno(root)
        self.assertTrue(
            any('@std/assert' in p and 'Take it off' in p for p in problems),
            problems)

    def test_the_repository_itself_passes(self):
        self.assertEqual(audit.check_deno(), [])


LOCK = '''# Generated by pub
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "3.6.1"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dev"
    source: hosted
    version: "0.19.0"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.8.0 <4.0.0"
'''


class LockfileReader(unittest.TestCase):
    def test_reads_names_versions_and_sources(self):
        packages = audit.pub_packages(LOCK)
        self.assertEqual(sorted(packages), ['archive', 'intl', 'sky_engine'])
        self.assertEqual(packages['archive']['version'], '3.6.1')
        self.assertEqual(packages['intl']['source'], 'hosted')
        self.assertEqual(packages['intl']['dependency'], 'direct main')

    def test_stops_at_the_sdks_block(self):
        # `sdks:` is a sibling of `packages:`, and a reader that ran on
        # would invent packages out of whatever follows.
        #
        # Asserting only `'dart' not in ...` against pub's own flat
        # `dart: ">=3.8.0 <4.0.0"` proved nothing: that line does not
        # match the package pattern anyway, so the assertion held with
        # the block-boundary check deleted. This fixture puts a block
        # after `packages:` that WOULD match.
        trailing = LOCK + '''  flutter:
    version: "3.32.0"
'''
        packages = audit.pub_packages(trailing)
        self.assertEqual(sorted(packages), ['archive', 'intl', 'sky_engine'])
        self.assertNotIn('flutter', packages)
        self.assertNotIn('dart', packages)

    def test_the_real_lockfile_parses_to_something_plausible(self):
        _problems, packages = audit.check_pub()
        self.assertGreater(len(packages), 100)
        self.assertIn('supabase_flutter', packages)

    def test_a_dependency_the_lockfile_never_resolved_is_reported(self):
        # The failure this catches: somebody adds a package to
        # pubspec.yaml, does not commit the regenerated lockfile, and CI
        # then builds a version nobody chose -- or fails on a machine
        # that resolves differently.
        root = workspace({
            'app/pubspec.lock': LOCK,
            'app/pubspec.yaml': '''name: iakauntan
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  ghost: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
''',
        })
        problems, _ = audit.check_pub(root)
        self.assertTrue(any('ghost' in p for p in problems), problems)
        # And the one that IS resolved is not reported.
        self.assertFalse(any('intl' in p for p in problems), problems)

    def test_a_lockfile_the_parser_cannot_read_is_a_failure(self):
        root = workspace({'app/pubspec.lock': 'packages:\n',
                          'app/pubspec.yaml': 'name: iakauntan\n'})
        problems, _ = audit.check_pub(root)
        self.assertTrue(
            any('parser and the file disagree' in p for p in problems),
            problems)

    def test_the_repository_itself_passes(self):
        problems, _ = audit.check_pub()
        self.assertEqual(problems, [])


class Advisories(unittest.TestCase):
    def test_a_hit_is_reported_against_the_package_that_has_it(self):
        packages = {'intl': {'version': '0.19.0', 'source': 'hosted'}}
        calls = []

        def fake(queries):
            calls.append(queries)
            return [{'vulns': [{'id': 'GHSA-fake-0001'}]}]

        findings, unchecked = advisories(packages, {}, fake)
        self.assertEqual(findings, ['Pub intl 0.19.0: GHSA-fake-0001'])
        self.assertEqual(calls[0][0]['package'],
                         {'ecosystem': 'Pub', 'name': 'intl'})
        self.assertEqual(unchecked, [])

    def test_no_vulns_is_no_finding(self):
        packages = {'intl': {'version': '0.19.0', 'source': 'hosted'}}
        findings, _ = advisories(packages, {}, lambda q: [{}])
        self.assertEqual(findings, [])

    def test_what_no_database_covers_is_named_rather_than_counted_clean(self):
        # @std/* is published to JSR only and OSV has no ecosystem for
        # it. Saying so is the difference between a check and a claim.
        findings, unchecked = advisories(
            {}, {'jsr:@std/assert@1': ['x.ts']}, lambda q: [])
        self.assertEqual(findings, [])
        self.assertEqual(len(unchecked), 1)
        self.assertIn('@std/assert', unchecked[0])

    def test_a_package_that_is_not_on_pub_dev_is_unchecked_too(self):
        packages = {'thing': {'version': '1.0.0', 'source': 'git'}}
        findings, unchecked = advisories(packages, {}, lambda q: [])
        self.assertEqual(findings, [])
        self.assertIn('not on pub.dev', unchecked[0])

    def test_the_supabase_client_is_asked_about_as_an_npm_package(self):
        seen = []

        def fake(queries):
            seen.extend(queries)
            return [{} for _ in queries]

        advisories({}, {'jsr:@supabase/supabase-js@2': ['x.ts']}, fake)
        self.assertEqual(seen[0]['package'],
                         {'ecosystem': 'npm', 'name': '@supabase/supabase-js'})
        self.assertEqual(seen[0]['version'], '2')

    def test_a_short_answer_is_an_error_rather_than_a_pass(self):
        # OSV answers positionally. A batch of forty that comes back
        # with thirty-nine results cannot be matched to what was asked,
        # and quietly zipping them would attribute one package's
        # advisory to another.
        packages = {'a': {'version': '1.0.0', 'source': 'hosted'},
                    'b': {'version': '1.0.0', 'source': 'hosted'}}
        with self.assertRaises(RuntimeError):
            advisories(packages, {}, lambda q: [{}])

    def test_a_long_answer_is_an_error_too(self):
        # The other direction of the same mismatch. Both are 'the batch
        # cannot be matched to what was asked', and a check that only
        # caught one of them would attribute advisories by luck.
        packages = {'a': {'version': '1.0.0', 'source': 'hosted'}}
        with self.assertRaises(RuntimeError):
            advisories(packages, {}, lambda q: [{}, {}])

    def test_an_unreachable_database_raises_instead_of_returning_nothing(self):
        def dead(request, timeout=0):
            raise OSError('connect: 403 from the proxy')

        with self.assertRaises(RuntimeError) as caught:
            audit.osv_query([{'package': {'ecosystem': 'Pub', 'name': 'x'},
                              'version': '1'}], attempts=1, opener=dead)
        self.assertIn('could not be reached', str(caught.exception))


class TheRunItself(unittest.TestCase):
    def test_offline_passes_on_this_repository_and_says_what_it_skipped(self):
        # The exit code is what CI reads. A run that found nothing and a
        # run that checked nothing both print reassuring text; only one
        # of them may return 0 while claiming to have audited anything.
        import contextlib
        import io

        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            code = audit.main(['--offline'])
        self.assertEqual(code, 0)
        self.assertIn('SKIPPED', out.getvalue())
        self.assertIn('Nothing about published vulnerabilities was checked',
                      out.getvalue())


def advisories(packages, deno, query):
    return audit.advisories_for(packages, deno, query=query)


if __name__ == '__main__':
    unittest.main(verbosity=2)
