-- =====================================================================
-- iAkauntan :: 0604 the register, asked properly
--
-- `0589` built the interim SSM lookup: a web session against
-- ssmsearch.com, reached in a way their terms of service prohibit,
-- while the official API was arranged. This is the official one --
-- SSM's Corporate Information Delivery Platform, CIDP v1.0.1, thirteen
-- endpoints behind a key and a secret.
--
-- It does not replace the interim provider yet. `SSM_PROVIDER` chooses,
-- and it defaults to `web`, because the subscription is still under
-- SSM's review and there is no key to use. The seam is here so that the
-- day the key arrives is a dashboard secret rather than a deploy.
--
-- ---------------------------------------------------------------------
-- Every call is charged
--
-- The development host is free and serves fixture data. Production is
-- billed per call against a points balance the whole platform shares.
-- That is the reason for all three of the things below and it is worth
-- saying once rather than three times: the cache, so the same answer is
-- not bought twice; the log, so a charge can be traced to the company
-- that asked for it; and the per-minute limit, which is a count of log
-- rows, so the record and the limit cannot disagree.
--
-- ---------------------------------------------------------------------
-- Why `searched_by` and not `user_id`
--
-- `0589` made this call and its reasoning holds here: a `user_id`
-- beside an `org_id` is read by `a_colleague_not_a_stranger.sql` as
-- work HANDED to somebody, and it wants a trigger checking the person
-- belongs to the company. Nobody is handed anything here. This is an
-- audit row naming who acted, which is what the `_by` suffix means
-- everywhere else in this schema.
--
-- The `org_id` IS kept, unlike `ssm_search_log`, and for a reason that
-- did not apply there: these calls cost money. Which company a charge
-- belongs to is the first question anybody will ask of this table, and
-- the rate limit is per company rather than per person because ten
-- members of staff at thirty lookups a minute each is the same bill as
-- one enthusiastic script.
-- =====================================================================

-- ---------------------------------------------------------------------
-- The log, which is also the rate limit and the bill
-- ---------------------------------------------------------------------
create table if not exists public.ssm_api_log (
  id             bigint generated by default as identity primary key,
  org_id         uuid references public.organizations (id) on delete set null,
  searched_by    uuid references auth.users (id) on delete set null,

  -- What the app asked for, and what was asked upstream. Both, because
  -- one edge action can dispatch to four different endpoints --
  -- `profile` picks by entity type -- and a charge is against the path.
  action         text not null,
  path           text not null,

  -- The reference sent as `x-Client-Ref-No` and echoed back. This is
  -- what SSM's own support will ask for.
  client_ref_no  text not null,
  request_ref_no text,

  status         integer,
  ok             boolean not null,

  -- auth | http | route | payload | upstream | network | parse. The
  -- client's own vocabulary, kept as text: it is somebody else's list
  -- of ways to fail and a new one should arrive as itself.
  error_kind     text,
  duration_ms    integer,

  -- The development host is free and production is charged. A row that
  -- did not say which would make the bill unreconcilable.
  base_url       text,

  created_at     timestamptz not null default now()
);

comment on table public.ssm_api_log is
  'Every call to SSM''s official Search API: which company asked, who, '
  'which endpoint, and what it cost in time. Service role only. '
  'Doubles as the rate limit — the per-minute count is a count of '
  'these rows, so the record and the limit cannot disagree.';

create index if not exists ssm_api_log_org_time_idx
  on public.ssm_api_log (org_id, created_at desc);

-- SSM's support asks for the reference, and nobody looking one up
-- knows which company it belonged to.
create index if not exists ssm_api_log_client_ref_idx
  on public.ssm_api_log (client_ref_no);

alter table public.ssm_api_log enable row level security;
revoke all on public.ssm_api_log from anon, authenticated;

-- ---------------------------------------------------------------------
-- The cache already exists; this widens it
--
-- `0589` created `ssm_search_cache` with `cache_key, provider, payload,
-- created_at, expires_at`, keyed on the normalised query. The official
-- API needs three more: WHICH action the row answers, the parameters it
-- answers for, and the host it came from.
--
-- The last one is not bookkeeping. The development host serves fixture
-- data for free and production serves the register for money, and an
-- answer from one handed back as an answer from the other is a wrong
-- company name on an invoice. It is part of the key the edge function
-- hashes, and it is recorded here so a row can be read afterwards.
--
-- All three are nullable: the rows the web provider has already written
-- have none of them, and a `not null` would mean dropping a cache that
-- is doing its job.
-- ---------------------------------------------------------------------
alter table public.ssm_search_cache
  add column if not exists action   text,
  add column if not exists params   jsonb,
  add column if not exists base_url text;

comment on column public.ssm_search_cache.action is
  'The ssm-api action this row answers. Null for rows written by the '
  'interim web provider, which has one kind of answer.';
comment on column public.ssm_search_cache.base_url is
  'Which SSM host answered. Part of the cache key: the free development '
  'host serves fixture data and production serves the register.';

-- ---------------------------------------------------------------------
-- Housekeeping
--
-- Expired rows are not read -- every lookup carries `expires_at > now()`
-- -- so this is about the table not growing without limit rather than
-- about correctness. Service role only, like everything else here.
-- ---------------------------------------------------------------------
create or replace function public.ssm_search_cache_purge()
returns integer
language sql
security definer
set search_path to 'pg_catalog', 'public', 'pg_temp'
as $function$
  with gone as (
    delete from public.ssm_search_cache where expires_at < now()
    returning 1
  )
  select count(*)::integer from gone;
$function$;

comment on function public.ssm_search_cache_purge() is
  'Deletes cache rows that have expired and returns how many. Expired '
  'rows are never read, so this is about the table not growing rather '
  'than about correctness. Service role only.';

revoke all on function public.ssm_search_cache_purge()
  from public, anon, authenticated;
grant execute on function public.ssm_search_cache_purge() to service_role;
